# Матрицы

## Определение
Матрица - это двухмерный массив чисел, организованный в виде строк и столбцов. Например, вот такая матрица 3x3 (три строки и три столбца):

$$
\begin{pmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9 
\end{pmatrix}
$$

## Создание Матрицы в Python

Мы можем легко создать матрицу с помощью модуля numpy в Python:

```python
import numpy as np

# Создаем матрицу 3x3
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(matrix)
```

## Основные Операции с Матрицами

### 1. Сложение Матриц

Две матрицы складываются, если они имеют одинаковую размерность. Сложение выполняется путем элементного сложения соответствующих элементов:

$$
\begin{pmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9 
\end{pmatrix}
+ 
\begin{pmatrix}
9 & 8 & 7 \\
6 & 5 & 4 \\
3 & 2 & 1 
\end{pmatrix}
=
\begin{pmatrix}
10 & 10 & 10 \\
10 & 10 & 10 \\
10 & 10 & 10 
\end{pmatrix}
$$

Пример в Python:

```python
matrix1 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

matrix2 = np.array([
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
])

# Сложение матриц
result_matrix = matrix1 + matrix2
print(result_matrix)
```

### 2. Умножение Матриц
Умножение матриц возможно, если число столбцов первой матрицы равно числу строк второй матрицы. Результирующая матрица имеет размерность (число строк первой матрицы) x (число столбцов второй матрицы).

$$
\begin{pmatrix}
1 & 2 \\
3 & 4
\end{pmatrix}
\times
\begin{pmatrix}
5 & 6 \\
7 & 8
\end{pmatrix}
=
\begin{pmatrix}
(1*5 + 2*7) & (1*6 + 2*8) \\
(3*5 + 4*7) & (3*6 + 4*8)
\end{pmatrix}
=
\begin{pmatrix}
19 & 22 \\
43 & 50
\end{pmatrix}
$$

Пример в Python:

```python
matrix1 = np.array([
    [1, 2],
    [3, 4]
])

matrix2 = np.array([
    [5, 6],
    [7, 8]
])

# Умножение матриц
result_matrix = np.dot(matrix1, matrix2)
print(result_matrix)
```

### 3. Транспонирование Матрицы

Транспонированная матрица получается путем замены строк на столбцы:

$$
\begin{pmatrix}
1 & 2 & 3 \\
4 & 5 & 6 
\end{pmatrix}
^T
=
\begin{pmatrix}
1 & 4 \\
2 & 5 \\
3 & 6
\end{pmatrix}
$$

Пример в Python:

```python
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# Транспонирование матрицы
transposed_matrix = matrix.T
print(transposed_matrix)
```

## **Rotate Image** (Задача #48 на LeetCode).

Дано матрицу `n x n`, то есть двумерный массив, представляющий изображение. Поверните изображение на 90 градусов по часовой стрелке.

### Пример 1
```
Вход:
[
  [1,2,3],
  [4,5,6],
  [7,8,9]
]
Выход:
[
  [7,4,1],
  [8,5,2],
  [9,6,3]
]
```

### Пример 2
```
Вход:
[
  [ 5, 1, 9,11],
  [ 2, 4, 8,10],
  [13, 3, 6, 7],
  [15,14,12,16]
]
Выход:
[
  [15,13, 2, 5],
  [14, 3, 4, 1],
  [12, 6, 8, 9],
  [16, 7,10,11]
]
```

### Решение

Повернуть матрицу на 90 градусов по часовой стрелке можно через два шага:
1. Транспонировать матрицу.
2. Развернуть каждую строку.

In [1]:
import numpy as np

def rotate(matrix):
    """
    Функция поворота матрицы на 90 градусов по часовой стрелке.
    
    :param matrix: List[List[int]] 
    """
    # Транспонирование матрицы
    n = len(matrix)
    for i in range(n):
        for j in range(i, n):
            matrix[i][j], matrix[j][i] = matrix[j][i], matrix[i][j]
    
    # Разворот каждой строки
    for i in range(n):
        matrix[i].reverse()

# Пример использования
matrix = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

rotate(matrix)

print(np.array(matrix))

[[7 4 1]
 [8 5 2]
 [9 6 3]]
